
# This file is from https://github.com/facebookresearch/detectron2/tree/main/projects/DensePose which is under Apache 2.0 license.


_BASE_: "Base-DensePose-RCNN-FPN.yaml"
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-101.pkl"
  RESNETS:
    DEPTH: 101
  ROI_DENSEPOSE_HEAD:
    NAME: "DensePoseDeepLabHead"
SOLVER:
  MAX_ITER: 130000
  STEPS: (100000, 120000)
